apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: nginx-app
  namespace: flux-system
spec:
  interval: 1m
  path: "../../nginx/base"
  prune: true
  sourceRef:
    kind: GitRepository
    name: FluxTest
  targetNamespace: default
