apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: nginx-deployment
  namespace: flux-system
spec:
  interval: 1m
  path: "./nginx/base"  # Correct path to your Nginx manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: FluxTest  # This should be your Git repository name
  targetNamespace: default  # Resources will be deployed in the default namespace
